package cli

import (
	_ "embed"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"go.yaml.in/yaml/v3"

	"github.com/codesweep-ai/campaign/internal/model"
)

// init scaffolds the files a campaign needs before it can be created: a profile,
// a mission, and one role brief per declared member.
//
// It exists because `validate` refuses a campaign whose briefs are missing, and
// an error that names what is absent should be followed by something that
// produces it. Otherwise the first thing a new operator meets is a dead end.
//
// The stubs are deliberately INCOMPLETE — blanks and bracketed choices, not
// prose that could be shipped unread. A scaffolder that emitted plausible
// briefs would produce fleets briefed with boilerplate nobody edited, and a
// member restates boilerplate as faithfully as it restates real intent. That is
// the same silent substitution the no-fallback rule exists to prevent, arriving
// by a different route.

//go:embed assets/stub-mission.md
var stubMission string

//go:embed assets/stub-orchestrator.md
var stubOrchestrator string

//go:embed assets/stub-agent.md
var stubAgent string

// profileHeader and authHint bracket the generated profile with the two things
// a generated file cannot supply: what to do with it, and the one stanza whose
// absence is not an error until it is a dead fleet.
const profileHeader = `# Campaign profile for {{.Campaign}} — generated by cs-campaign init.
#
# The fleet below is what you asked for. What is missing is credentials: see the
# bottom of this file. Briefs live in roles/, one per member, and the mission in
# mission.md; all three are found by position beside this file.
`

const authHint = `
# Credentials — REQUIRED before this fleet can do anything.
#
# Add an auth block to every member. Values are never written here: apiKeyFromEnv
# names host environment variables, and the first one that is actually set is used.
#
#   orchestrator:
#     auth:
#       apiKeyFromEnv: [OPENAI_API_KEY]
#
# For a CLI that authenticates from an existing host login instead:
#
#     auth:
#       inheritAgentLogin: [claude]
#
# Inherited logins expire in hours, so check yours immediately before create.
`

type stubData struct {
	Campaign string
	Member   string
}

func (a *app) initCmd() *cobra.Command {
	opts := new(createOpts)
	var dir string
	cmd := &cobra.Command{
		Use:   "init <campaign>",
		Short: "Scaffold a campaign's profile, mission and role briefs",
		Args:  cobra.ExactArgs(1),
		RunE: func(c *cobra.Command, args []string) error {
			name := args[0]
			// The fleet is parsed by the SAME function create uses, so a
			// scaffolded profile cannot describe a fleet create would reject.
			profile, err := profileFromFlags(opts.orchestrator, opts.agents, opts.agentCLI, opts.count, opts.repo)
			if err != nil {
				return err
			}
			target := dir
			if target == "" {
				target = name
			}
			return scaffoldCampaign(c.OutOrStdout(), target, name, profile)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&dir, "dir", "", "directory to scaffold into (default: the campaign name)")
	flags.StringVar(&opts.orchestrator, "orchestrator", "", "orchestrator CLI")
	flags.StringSliceVar(&opts.agents, "agent", nil, "agent name=cli (repeatable)")
	flags.StringVar(&opts.agentCLI, "agent-cli", "", "CLI for homogeneous agents")
	flags.IntVar(&opts.count, "agents", 0, "number of homogeneous agents")
	flags.StringVar(&opts.repo, "repo", "", "repository cloned into every member")
	return cmd
}

// scaffoldCampaign writes the profile and every brief, refusing to overwrite.
//
// Refusing matters more than it looks: re-running init in a directory where the
// briefs have been filled in would silently replace considered work with blanks,
// and the resulting campaign would still validate and still create.
func scaffoldCampaign(out io.Writer, dir, name string, profile model.Profile) error {
	roles := filepath.Join(dir, rolesDirName)
	if err := os.MkdirAll(roles, 0o755); err != nil {
		return err
	}

	encoded, err := yaml.Marshal(profile)
	if err != nil {
		return err
	}
	// The scaffolded profile declares no credentials, because there is no safe
	// default to guess. Left bare it would create a fleet whose members cannot
	// authenticate, and that failure looks exactly like a broken fleet — so the
	// file says where they go rather than leaving the operator to find out at the
	// first turn. Comments survive the parser untouched.
	profileText := render(profileHeader, stubData{Campaign: name}) + string(encoded) + authHint

	files := map[string]string{
		filepath.Join(dir, "profile.yaml"):      profileText,
		filepath.Join(dir, missionFileName):     render(stubMission, stubData{Campaign: name}),
		filepath.Join(roles, "orchestrator.md"): render(stubOrchestrator, stubData{Campaign: name}),
	}
	for _, member := range sortedNames(profile.Agents) {
		files[filepath.Join(roles, member+".md")] = render(stubAgent, stubData{Campaign: name, Member: member})
	}

	var existing []string
	for path := range files {
		if _, err := os.Stat(path); err == nil {
			existing = append(existing, path)
		}
	}
	if len(existing) > 0 {
		return fmt.Errorf("refusing to overwrite:\n  %s\nremove them, or scaffold into a different --dir",
			strings.Join(sortedStrings(existing), "\n  "))
	}

	for _, path := range sortedStrings(keysOf(files)) {
		if err := os.WriteFile(path, []byte(files[path]), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(out, "wrote %s\n", path)
	}
	fmt.Fprintf(out, "\nFill in the blanks, then:\n  cs-campaign validate %s\n", filepath.Join(dir, "profile.yaml"))
	return nil
}

func render(text string, data stubData) string {
	t, err := template.New("stub").Parse(text)
	if err != nil {
		return text
	}
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return text
	}
	return b.String()
}

func keysOf(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

func sortedStrings(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
