package cli

// The upstream surface — the cs-sandbox that builds the microVMs, the agent
// tools it ships, and the sibling cs- tools this repository names — is checked
// against ONE reference: the go.mod embedded in this binary at build time.
//
// That reference cannot drift. It is not recorded by an operator, not
// regenerated by a make target, and not read off the host: it is the same
// manifest the toolchain resolved when this executable was linked, carried
// inside it. A cs-campaign built from a tree whose go.mod names cs-sandbox X
// cannot be made to expect anything but X, which is the whole property the
// hand-written pin it replaced could never have.
//
// Three questions, and each is answered by whoever can actually answer it:
//
//  1. Is the cs-sandbox on PATH the one this build was made against? Only
//     cs-campaign knows, because only cs-campaign holds the pin. Fatal: a
//     campaign is built by that binary, and running on an unnamed one is the
//     state `create` exists to refuse.
//  2. Are the agent tools the right ones? cs-sandbox answers that, for its own
//     PATH, in its own `doctor`. It ships them, so it is the only thing that
//     can. cs-campaign asks it for the hashes (`agent-tools --json`) and uses
//     them for the plane sandbox cannot see: the inside of a member.
//  3. Are the sibling cs- tools the ones this build names? Reported, never
//     fatal. cs-vcr records and replays cassettes, and the rest are developer
//     gates; a host that runs real campaigns has none of them and is complete.
//
// The guest image id is NOT covered: its tag is a per-build counter with no
// stable reference to resolve, so pinning it needs engine-specific plumbing,
// left for whoever does that migration.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/codesweep-ai/campaign"
	"github.com/codesweep-ai/campaign/internal/model"
)

// sandboxModule is the one pin whose absence from PATH stops a campaign.
const sandboxModule = "github.com/codesweep-ai/sandbox"

// siblingTools are the other cs- tools this repository pins. cs-vcr is the
// replay surface; the rest are the gates `make check` runs. None is needed to
// run a campaign, so none of them is fatal here — but a copy on PATH at a
// version this build does not name will disagree with `go tool` about
// something, and nothing else would say so.
var siblingTools = []struct{ bin, module string }{
	{"cs-vcr", "github.com/codesweep-ai/vcr"},
	{"cs-lint", "github.com/codesweep-ai/lint"},
	{"cs-ledger", "github.com/codesweep-ai/ledger"},
	{"cs-tracer", "github.com/codesweep-ai/tracer"},
}

// toolPins reads the cs- versions out of the embedded manifest, as module path
// -> version.
//
// Scanned rather than parsed: a require line is "path version" once trimmed,
// which is all this needs, and it keeps the check free of a module-file parser
// whose failure modes would be a second thing to reason about.
func toolPins() map[string]string {
	pins := map[string]string{}
	for line := range strings.SplitSeq(campaign.GoMod, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || !strings.HasPrefix(fields[0], "github.com/codesweep-ai/") {
			continue
		}
		if strings.HasPrefix(fields[1], "v") {
			pins[fields[0]] = fields[1]
		}
	}
	return pins
}

// upstreamReport is what one look at the host surface found, in the three
// grades it can be read as.
//
// Deviations refuse a create. Warnings are true findings that do not: a sibling
// on PATH at a version this build does not name will disagree with `go tool`
// about something, and the operator should know, but no campaign is worse for
// it. Notes are the good news, including a sibling that is simply absent.
//
// Kept apart because they print differently, and a warning rendered with an
// `ok` prefix is worse than not printing it at all.
type upstreamReport struct {
	SandboxVersion string
	Deviations     []string
	Warnings       []string
	Notes          []string
}

// toolVersion picks the version out of `<tool> version`, which every tool in
// the family prints as `<name> <version> (<platform>, <toolchain>)`.
//
// The whole second field, +dirty included. Go's build info appends that to a
// binary built from a modified tree, and a module version cannot carry it, so
// such a build can never equal a pin. That is the right answer rather than a
// formatting problem to trim away: a dirty build is not the revision it names,
// and it is exactly the build someone installs mid-campaign without meaning to.
func toolVersion(out string) string {
	fields := strings.Fields(out)
	if len(fields) < 2 {
		return ""
	}
	// A version token starts with `v` or a digit: v0.0.0-<stamp> from a module
	// pseudo-version, 0.0.1-snapshot-<rev> from the older stamp, or the bare
	// short commit `git describe --always` falls back to. Anything else is not
	// a version line at all, and reading its second word as one would report
	// "on PATH is a" at an operator who printed prose.
	v := fields[1]
	if v == "" || !(v[0] == 'v' || (v[0] >= '0' && v[0] <= '9')) {
		return ""
	}
	return v
}

// probeVersion asks a tool on PATH what it is.
func probeVersion(ctx context.Context, bin string) string {
	out, err := exec.CommandContext(ctx, bin, "version").Output()
	if err != nil {
		return ""
	}
	return toolVersion(string(out))
}

// verifyUpstream compares the host surface to this build's manifest.
func (a *app) verifyUpstream(ctx context.Context) upstreamReport {
	pins := toolPins()
	report := upstreamReport{SandboxVersion: "(unknown)"}

	want := pins[sandboxModule]
	switch reported, err := a.sandbox.version(ctx); {
	case err != nil:
		report.Deviations = append(report.Deviations,
			fmt.Sprintf("cs-sandbox version probe failed: %v (this build was made against %s)", err, want))
	default:
		got := toolVersion(reported)
		switch {
		case got == "":
			report.Deviations = append(report.Deviations,
				fmt.Sprintf("unrecognized cs-sandbox version output %q (this build was made against %s)", strings.TrimSpace(reported), want))
		case want == "":
			// Unreachable through a built binary, which always carries the
			// manifest that required cs-sandbox. Reported rather than ignored
			// because the alternative is comparing against "" and calling every
			// host a match.
			report.SandboxVersion = got
			report.Deviations = append(report.Deviations,
				"this build's go.mod names no cs-sandbox version to check against")
		case got != want:
			report.SandboxVersion = got
			report.Deviations = append(report.Deviations,
				fmt.Sprintf("cs-sandbox on PATH is %s, this build was made against %s — install the one this build names:  go install %s/cmd/cs-sandbox@%s",
					got, want, sandboxModule, want))
		default:
			report.SandboxVersion = got
		}
	}

	var absent []string
	for _, t := range siblingTools {
		if _, err := exec.LookPath(t.bin); err != nil {
			absent = append(absent, t.bin)
			continue
		}
		want := pins[t.module]
		got := probeVersion(ctx, t.bin)
		switch {
		case want == "":
			report.Warnings = append(report.Warnings, t.bin+" is on PATH but this build's go.mod pins no version for it")
		case got == "":
			report.Warnings = append(report.Warnings, t.bin+" is on PATH but did not answer `"+t.bin+" version`, so it cannot be identified")
		case got != want:
			report.Warnings = append(report.Warnings, fmt.Sprintf("%s on PATH is %s, this build names %s — `go install %s/cmd/%s@%s` to agree with it",
				t.bin, got, want, t.module, t.bin, want))
		default:
			// Said out loud, not passed over in silence. A check that prints
			// nothing when it matches leaves "compared, and they agree"
			// indistinguishable from "never compared".
			report.Notes = append(report.Notes, t.bin+" on PATH matches this build ("+want+")")
		}
	}
	if len(absent) > 0 {
		report.Notes = append(report.Notes, "not on PATH (fine — a campaign needs none of them): "+strings.Join(absent, " "))
	}
	return report
}

// agentToolHashes asks cs-sandbox what agent tools it ships, and what they
// should hash to.
//
// From cs-sandbox rather than derived here, because cs-sandbox is what puts
// those files on a host AND what seeds them into every member. Deriving them on
// this side would mean a second description of the same bytes, which is the
// arrangement that let a host read as correct while three guests ran something
// else.
func (a *app) agentToolHashes(ctx context.Context) (map[string]string, error) {
	out, err := a.sandbox.output(ctx, "agent-tools", "--json")
	if err != nil {
		return nil, fmt.Errorf("cs-sandbox agent-tools --json: %w (this build expects cs-sandbox %s, which has it)", err, toolPins()[sandboxModule])
	}
	var answer struct {
		Version string            `json:"version"`
		Tools   map[string]string `json:"tools"`
	}
	if err := json.Unmarshal(out, &answer); err != nil {
		return nil, fmt.Errorf("cs-sandbox agent-tools --json returned unreadable JSON: %w", err)
	}
	if len(answer.Tools) == 0 {
		return nil, errors.New("cs-sandbox agent-tools --json named no tools at all")
	}
	return answer.Tools, nil
}

// reportUpstream prints the upstream verdict for doctor: an error return means
// doctor must fail.
func (a *app) reportUpstream(ctx context.Context, out func(string)) error {
	report := a.verifyUpstream(ctx)
	if len(report.Deviations) > 0 {
		return fmt.Errorf("upstream surface is not the one this cs-campaign was built against:\n  %s\ndo not campaign on a surface this build does not name",
			strings.Join(report.Deviations, "\n  "))
	}
	out("ok  cs-sandbox on PATH is the one this build names: " + report.SandboxVersion)
	for _, note := range report.Notes {
		out("ok  " + note)
	}
	// Last, and NOT as an ok line. A finding rendered with the badge of good
	// news is worse than one not printed at all.
	for _, warning := range report.Warnings {
		out("WARN " + warning)
	}
	return nil
}

// gateUpstream enforces the manifest before any provisioning: a deviating
// surface refuses create unless the operator explicitly accepts, and either way
// the verdict is recorded on the campaign.
func (a *app) gateUpstream(ctx context.Context, out io.Writer, campaign *model.Campaign, accept bool) error {
	report := a.verifyUpstream(ctx)
	campaign.Upstream = &model.UpstreamCheck{
		CheckedAt:      time.Now().UTC(),
		SandboxVersion: report.SandboxVersion,
		Deviations:     report.Deviations,
		Warnings:       report.Warnings,
		Notes:          report.Notes,
		Accepted:       accept && len(report.Deviations) > 0,
	}
	if len(report.Deviations) == 0 {
		return nil
	}
	if !accept {
		return fmt.Errorf("upstream surface is not the one this cs-campaign was built against:\n  %s\ninstall the surface this build names, or --accept-upstream-change to proceed with the deviation recorded",
			strings.Join(report.Deviations, "\n  "))
	}
	fmt.Fprintf(out, "WARN proceeding on a surface this build does not name, recorded on the campaign:\n  %s\n", strings.Join(report.Deviations, "\n  "))
	return nil
}

// archiveUpstreamFingerprint writes the end-of-campaign surface snapshot into
// the archive. Best-effort by design: probe failures are recorded inside the
// file, because host-surface metadata must not block evidence collection the
// way a missing member channel does.
func (a *app) archiveUpstreamFingerprint(ctx context.Context, root string) {
	report := a.verifyUpstream(ctx)
	snapshot := struct {
		At             time.Time         `json:"at"`
		BuiltAgainst   map[string]string `json:"builtAgainst"`
		SandboxVersion string            `json:"sandboxVersion"`
		Deviations     []string          `json:"deviations,omitempty"`
		Warnings       []string          `json:"warnings,omitempty"`
		Notes          []string          `json:"notes,omitempty"`
		AgentTools     map[string]string `json:"agentTools,omitempty"`
		Error          string            `json:"error,omitempty"`
	}{
		At:             time.Now().UTC(),
		BuiltAgainst:   toolPins(),
		SandboxVersion: report.SandboxVersion,
		Deviations:     report.Deviations,
		Warnings:       report.Warnings,
		Notes:          report.Notes,
	}
	if tools, err := a.agentToolHashes(ctx); err != nil {
		snapshot.Error = err.Error()
	} else {
		snapshot.AgentTools = tools
	}
	if encoded, err := json.MarshalIndent(snapshot, "", "  "); err == nil {
		_ = os.WriteFile(filepath.Join(root, "upstream-fingerprint.json"), append(encoded, '\n'), 0o600)
	}
}

// sortedToolNames orders a hash table so a probe and a report read the same way
// twice.
func sortedToolNames(tools map[string]string) []string {
	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
