package cli

// The upstream surface — the cs-sandbox that builds the microVMs, the agent
// tools it ships, and the sibling cs- tools this repository names — is checked
// against ONE reference: the go.mod embedded in this binary at build time.
//
// That reference cannot drift. It is not recorded by an operator, not
// regenerated by a make target, and not read off the host: it is the same
// manifest the toolchain resolved when this executable was linked, carried
// inside it. A cs-campaign built from a tree whose go.mod names cs-sandbox X
// cannot be made to expect anything but X, which is the whole property the
// hand-written pin it replaced could never have.
//
// Three questions, and each is answered by whoever can actually answer it:
//
//  1. Is the cs-sandbox on PATH the one this build was made against? Only
//     cs-campaign knows, because only cs-campaign holds the pin. Fatal: a
//     campaign is built by that binary, and running on an unnamed one is the
//     state `create` exists to refuse.
//  2. Are the agent tools the right ones? cs-sandbox ships them, so it is the
//     only thing that can say what they should hash to. cs-campaign asks it
//     (`agent-tools --json`) and holds both planes to that one answer: this
//     host's PATH in `doctor`, since cs-campaign drives its members through
//     those tools, and the inside of each member in `doctor <campaign>`.
//  3. Are the developer tools the ones this build names? Reported, never
//     fatal. cs-vcr records and replays cassettes, cs-npmrevs serves the
//     viewer's npm packages, and the rest are the gates `make check` runs; a
//     host that runs real campaigns has none of them and is complete.
//
// `doctor` prints these in the groups `cs-sandbox doctor` prints, in the same
// words: the cs-sandbox pin under "cs-sandbox", then "agent tools", "agent
// CLIs" and "developer tools".
//
// The guest image id is NOT covered: its tag is a per-build counter with no
// stable reference to resolve, so pinning it needs engine-specific plumbing,
// left for whoever does that migration.

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/codesweep-ai/campaign"
	"github.com/codesweep-ai/campaign/internal/model"
)

// sandboxModule is the one pin whose absence from PATH stops a campaign.
const sandboxModule = "github.com/codesweep-ai/sandbox"

// siblingTools are the other cs- tools this repository pins, which doctor
// reports as "developer tools". cs-vcr is the replay surface, cs-npmrevs
// serves the viewer's npm packages, and the rest are the gates `make check`
// runs. None is needed to run a campaign, so none of them is fatal here — but a
// copy on PATH at a version this build does not name will disagree with `go
// tool` about something, and nothing else would say so.
var siblingTools = []struct{ bin, module string }{
	{"cs-vcr", "github.com/codesweep-ai/vcr"},
	{"cs-lint", "github.com/codesweep-ai/lint"},
	{"cs-ledger", "github.com/codesweep-ai/ledger"},
	{"cs-tracer", "github.com/codesweep-ai/tracer"},
	{"cs-npmrevs", "github.com/codesweep-ai/npmrevs"},
}

// toolPins reads the cs- versions out of the embedded manifest, as module path
// -> version.
//
// Scanned rather than parsed: a require line is "path version" once trimmed,
// which is all this needs, and it keeps the check free of a module-file parser
// whose failure modes would be a second thing to reason about.
func toolPins() map[string]string {
	pins := map[string]string{}
	for line := range strings.SplitSeq(campaign.GoMod, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || !strings.HasPrefix(fields[0], "github.com/codesweep-ai/") {
			continue
		}
		if strings.HasPrefix(fields[1], "v") {
			pins[fields[0]] = fields[1]
		}
	}
	return pins
}

// upstreamReport is what one look at the host surface found, in the three
// grades it can be read as.
//
// Deviations refuse a create. Warnings are true findings that do not: a sibling
// on PATH at a version this build does not name will disagree with `go tool`
// about something, and the operator should know, but no campaign is worse for
// it. Notes are the good news, including a sibling that is simply absent.
//
// Kept apart because they print differently, and a warning rendered with an
// `ok` prefix is worse than not printing it at all.
type upstreamReport struct {
	SandboxVersion string
	Deviations     []string
	Warnings       []string
	Notes          []string
}

// toolVersion picks the version out of `<tool> version`, which every tool in
// the family prints as `<name> <version> (<platform>, <toolchain>)`.
//
// The whole second field, +dirty included. Go's build info appends that to a
// binary built from a modified tree, and a module version cannot carry it, so
// such a build can never equal a pin. That is the right answer rather than a
// formatting problem to trim away: a dirty build is not the revision it names,
// and it is exactly the build someone installs mid-campaign without meaning to.
func toolVersion(out string) string {
	fields := strings.Fields(out)
	if len(fields) < 2 {
		return ""
	}
	// A version token starts with `v` or a digit: v0.0.0-<stamp> from a module
	// pseudo-version, 0.0.1-snapshot-<rev> from the older stamp, or the bare
	// short commit `git describe --always` falls back to. Anything else is not
	// a version line at all, and reading its second word as one would report
	// "on PATH is a" at an operator who printed prose.
	v := fields[1]
	if v == "" || !(v[0] == 'v' || (v[0] >= '0' && v[0] <= '9')) {
		return ""
	}
	return v
}

// probeVersion asks a tool on PATH what it is.
func probeVersion(ctx context.Context, bin string) string {
	out, err := exec.CommandContext(ctx, bin, "version").Output()
	if err != nil {
		return ""
	}
	return toolVersion(string(out))
}

// verifyUpstream compares the host surface to this build's manifest.
func (a *app) verifyUpstream(ctx context.Context) upstreamReport {
	pins := toolPins()
	report := upstreamReport{SandboxVersion: "(unknown)"}

	want := pins[sandboxModule]
	switch reported, err := a.sandbox.version(ctx); {
	case err != nil:
		report.Deviations = append(report.Deviations,
			fmt.Sprintf("cs-sandbox version probe failed: %v (this build pins %s)", err, want))
	default:
		got := toolVersion(reported)
		switch {
		case got == "":
			report.Deviations = append(report.Deviations,
				fmt.Sprintf("unrecognized cs-sandbox version output %q (this build pins %s)", strings.TrimSpace(reported), want))
		case want == "":
			// Unreachable through a built binary, which always carries the
			// manifest that required cs-sandbox. Reported rather than ignored
			// because the alternative is comparing against "" and calling every
			// host a match.
			report.SandboxVersion = got
			report.Deviations = append(report.Deviations,
				"this build's go.mod pins no cs-sandbox version to check against")
		case got != want:
			report.SandboxVersion = got
			report.Deviations = append(report.Deviations,
				fmt.Sprintf("cs-sandbox on PATH is %s, this build pins %s — install the pinned one:  go install %s/cmd/cs-sandbox@%s",
					got, want, sandboxModule, want))
		default:
			report.SandboxVersion = got
		}
	}

	var absent []string
	for _, t := range siblingTools {
		if _, err := exec.LookPath(t.bin); err != nil {
			absent = append(absent, t.bin)
			continue
		}
		want := pins[t.module]
		got := probeVersion(ctx, t.bin)
		switch {
		case want == "":
			report.Warnings = append(report.Warnings, t.bin+" is on PATH but this build's go.mod pins no version for it — run:  go get -tool "+t.module+"/cmd/"+t.bin+"@main")
		case got == "":
			report.Warnings = append(report.Warnings, t.bin+" is on PATH but did not answer `"+t.bin+" version` — it cannot be identified")
		case got != want:
			report.Warnings = append(report.Warnings, fmt.Sprintf("%s on PATH is %s, this build pins %s — install the pinned one:  go install %s/cmd/%s@%s",
				t.bin, got, want, t.module, t.bin, want))
		default:
			// Said out loud, not passed over in silence. A check that prints
			// nothing when it matches leaves "compared, and they agree"
			// indistinguishable from "never compared".
			report.Notes = append(report.Notes, t.bin+" on PATH matches the pin ("+want+")")
		}
	}
	if len(absent) > 0 {
		report.Notes = append(report.Notes, "not on PATH (fine — nothing here needs them): "+strings.Join(absent, " "))
	}
	return report
}

// agentToolHashes asks cs-sandbox what agent tools it ships, and what they
// should hash to.
//
// From cs-sandbox rather than derived here, because cs-sandbox is what puts
// those files on a host AND what seeds them into every member. Deriving them on
// this side would mean a second description of the same bytes, which is the
// arrangement that let a host read as correct while three guests ran something
// else.
func (a *app) agentToolHashes(ctx context.Context) (map[string]string, error) {
	out, err := a.sandbox.output(ctx, "agent-tools", "--json")
	if err != nil {
		return nil, fmt.Errorf("cs-sandbox agent-tools --json: %w (this build expects cs-sandbox %s, which has it)", err, toolPins()[sandboxModule])
	}
	var answer struct {
		Version string            `json:"version"`
		Tools   map[string]string `json:"tools"`
	}
	if err := json.Unmarshal(out, &answer); err != nil {
		return nil, fmt.Errorf("cs-sandbox agent-tools --json returned unreadable JSON: %w", err)
	}
	if len(answer.Tools) == 0 {
		return nil, errors.New("cs-sandbox agent-tools --json named no tools at all")
	}
	return answer.Tools, nil
}

// reportSandboxPin writes the cs-sandbox half of the upstream verdict into the
// doctor's "cs-sandbox" group. A deviation is a failed check, which is what
// makes doctor exit non-zero.
func reportSandboxPin(p *doctorPrinter, report upstreamReport) {
	if len(report.Deviations) == 0 {
		p.ok("cs-sandbox on PATH matches the pin (%s)", report.SandboxVersion)
	}
	for _, deviation := range report.Deviations {
		// The deviation already ends in the command that fixes it. A second
		// clause appended here ran the two together into one unreadable line,
		// and a NO in a doctor report already says not to proceed.
		p.bad("%s", deviation)
	}
}

// reportDeveloperTools writes the sibling half into the "developer tools"
// group. Nothing in it fails doctor: a campaign runs none of these tools.
func reportDeveloperTools(p *doctorPrinter, report upstreamReport) {
	for _, note := range report.Notes {
		p.ok("%s", note)
	}
	// Last within the group, so the lines an operator may want to act on are
	// the ones nearest the summary.
	for _, warning := range report.Warnings {
		p.warn("%s", warning)
	}
}

// reportAgentTools holds the agent tools on this host's PATH to what the
// cs-sandbox on PATH says it ships, in the words `cs-sandbox doctor` uses for
// the same check. Required here, where sandbox calls them optional: cs-campaign
// starts every member's turns through them, and cs-<cli>-remote copies its own
// cs-<cli>-turn into the member it drives, so a stale host copy reaches the
// guests too.
//
// A cs-sandbox that cannot answer leaves presence as the only check. That
// cs-sandbox is already a failure in the group above, so the reason is a
// warning here rather than a second failure for one cause.
func (a *app) reportAgentTools(ctx context.Context, p *doctorPrinter, sandboxVersion string) {
	const install = "cs-sandbox install-agent-tools"
	shipped, err := a.agentToolHashes(ctx)
	if err != nil {
		var missing []string
		for _, cli := range []string{"claude", "codex", "opencode"} {
			for _, suffix := range []string{"-remote", "-remote-output", "-turn"} {
				if _, err := exec.LookPath("cs-" + cli + suffix); err != nil {
					missing = append(missing, "cs-"+cli+suffix)
				}
			}
		}
		if len(missing) > 0 {
			p.bad("missing from PATH: %s — install them:  %s", strings.Join(missing, " "), install)
		}
		p.warn("cannot compare them with what cs-sandbox ships: %v", err)
		return
	}
	var missing, differing []string
	for _, name := range sortedToolNames(shipped) {
		path, err := exec.LookPath(name)
		if err != nil {
			missing = append(missing, name)
			continue
		}
		content, err := os.ReadFile(path)
		if err != nil {
			differing = append(differing, fmt.Sprintf("%s unreadable at %s", name, path))
			continue
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(content)); got != shipped[name] {
			differing = append(differing, fmt.Sprintf("%s differs (ships %.12s…, on PATH %.12s…)", name, shipped[name], got))
		}
	}
	switch {
	case len(missing) == len(shipped):
		p.bad("not on PATH — install them:  %s", install)
		return
	case len(missing) == 0 && len(differing) == 0:
		p.ok("the %d on PATH match cs-sandbox %s", len(shipped), sandboxVersion)
		return
	}
	if len(missing) > 0 {
		p.bad("missing from PATH: %s — install them:  %s", strings.Join(missing, " "), install)
	}
	if len(differing) > 0 {
		p.bad("on PATH but not the ones cs-sandbox %s ships:\n      %s\n      reinstall them:  %s",
			sandboxVersion, strings.Join(differing, "\n      "), install)
	}
}

// reportAgentCLIs names which agent CLIs this host has. Nothing here runs
// them: they are how you sign in on this host, which is where a login a member
// borrows or copies comes from. Every line is ok, as in `cs-sandbox doctor`.
func reportAgentCLIs(p *doctorPrinter) {
	var present, absent []string
	for _, cli := range []string{"claude", "codex", "opencode"} {
		if _, err := exec.LookPath(cli); err != nil {
			absent = append(absent, cli)
		} else {
			present = append(present, cli)
		}
	}
	if len(present) > 0 {
		p.ok("on PATH: %s", strings.Join(present, " "))
	}
	if len(absent) > 0 {
		p.ok("not on PATH (fine — nothing here needs them): %s", strings.Join(absent, " "))
	}
}

// gateUpstream enforces the manifest before any provisioning: a deviating
// surface refuses create unless the operator explicitly accepts, and either way
// the verdict is recorded on the campaign.
func (a *app) gateUpstream(ctx context.Context, out io.Writer, campaign *model.Campaign, accept bool) error {
	report := a.verifyUpstream(ctx)
	campaign.Upstream = &model.UpstreamCheck{
		CheckedAt:      time.Now().UTC(),
		SandboxVersion: report.SandboxVersion,
		Deviations:     report.Deviations,
		Warnings:       report.Warnings,
		Notes:          report.Notes,
		Accepted:       accept && len(report.Deviations) > 0,
	}
	if len(report.Deviations) == 0 {
		return nil
	}
	if !accept {
		return fmt.Errorf("upstream surface is not the one this cs-campaign was built against:\n  %s\ninstall the surface this build names, or --accept-upstream-change to proceed with the deviation recorded",
			strings.Join(report.Deviations, "\n  "))
	}
	fmt.Fprintf(out, "WARN proceeding on a surface this build does not name, recorded on the campaign:\n  %s\n", strings.Join(report.Deviations, "\n  "))
	return nil
}

// archiveUpstreamFingerprint writes the end-of-campaign surface snapshot into
// the archive. Best-effort by design: probe failures are recorded inside the
// file, because host-surface metadata must not block evidence collection the
// way a missing member channel does.
func (a *app) archiveUpstreamFingerprint(ctx context.Context, root string) {
	report := a.verifyUpstream(ctx)
	snapshot := struct {
		At             time.Time         `json:"at"`
		BuiltAgainst   map[string]string `json:"builtAgainst"`
		SandboxVersion string            `json:"sandboxVersion"`
		Deviations     []string          `json:"deviations,omitempty"`
		Warnings       []string          `json:"warnings,omitempty"`
		Notes          []string          `json:"notes,omitempty"`
		AgentTools     map[string]string `json:"agentTools,omitempty"`
		Error          string            `json:"error,omitempty"`
	}{
		At:             time.Now().UTC(),
		BuiltAgainst:   toolPins(),
		SandboxVersion: report.SandboxVersion,
		Deviations:     report.Deviations,
		Warnings:       report.Warnings,
		Notes:          report.Notes,
	}
	if tools, err := a.agentToolHashes(ctx); err != nil {
		snapshot.Error = err.Error()
	} else {
		snapshot.AgentTools = tools
	}
	if encoded, err := json.MarshalIndent(snapshot, "", "  "); err == nil {
		_ = os.WriteFile(filepath.Join(root, "upstream-fingerprint.json"), append(encoded, '\n'), 0o600)
	}
}

// sortedToolNames orders a hash table so a probe and a report read the same way
// twice.
func sortedToolNames(tools map[string]string) []string {
	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
