package cli

// The descriptions a site's AGENTS.md gives for every field of run-data.json
// and facts.json. TestReferencesCoverTheTypes fails when a field is added
// without one, or one outlives its field. A path with an empty description is
// listed alone.

var runDocs = map[string]string{
	"schemaVersion":                            "the version of this document's shape",
	"campaign":                                 "the campaign as its record states it",
	"campaign.name":                            "",
	"campaign.id":                              "",
	"campaign.createdAt":                       "when the campaign was created",
	"campaign.updatedAt":                       "when its record last changed",
	"campaign.outcome":                         "the outcome the orchestrator's mission reply claims, such as `campaign-met`. A claim, which the issues can contradict",
	"campaign.outcomeAt":                       "when that reply was written",
	"campaign.policy":                          "the recovery policy the run used; each field is in the manual's policy table",
	"campaign.policy.continueAttempts":         "",
	"campaign.policy.restarts":                 "",
	"campaign.policy.elapsedSeconds":           "",
	"campaign.policy.blindProbes":              "",
	"campaign.policy.pollSeconds":              "",
	"campaign.policy.settlingSeconds":          "",
	"campaign.policy.providerWaitSeconds":      "",
	"campaign.policy.stallSeconds":             "",
	"nodes":                                    "the team, orchestrator first: `name`, `role`, `cli`, `model`, `effort`",
	"nodes[].name":                             "",
	"nodes[].role":                             "",
	"nodes[].cli":                              "",
	"nodes[].model":                            "",
	"nodes[].effort":                           "",
	"events":                                   "every protocol event in time order",
	"events[].node":                            "the node whose channel it is on; an accept, plan or assessment is the orchestrator's",
	"events[].type":                            "`open`, `continue`, `restart`, `reply`, `verdict`, `accept`, `plan` or `assessment`",
	"events[].at":                              "when, to the second",
	"events[].dispatch":                        "the dispatch it belongs to",
	"events[].seq":                             "a continue's or restart's number within its dispatch",
	"events[].file":                            "the message file it came from",
	"events[].phase":                           "a reply's phase, such as `done`",
	"events[].outcome":                         "a verdict's outcome",
	"events[].text":                            "a log entry's text; on an accept, the node accepted",
	"events[].addr":                            "the event's address on the page",
	"spans":                                    "one per dispatch",
	"spans[].id":                               "the dispatch, `dNNN` per member or `m1` for the mission",
	"spans[].node":                             "",
	"spans[].openedAt":                         "",
	"spans[].repliedAt":                        "absent when never replied to",
	"spans[].acceptedAt":                       "when the orchestrator's log accepted it",
	"spans[].phase":                            "the reply's phase",
	"spans[].continues":                        "continues the harness sent on it",
	"spans[].restarts":                         "restarts the harness sent on it",
	"spans[].addr":                             "the address that picks the dispatch and zooms to it",
	"log":                                      "the orchestrator's own log: claims, not channel traffic",
	"log[].at":                                 "",
	"log[].kind":                               "",
	"log[].text":                               "",
	"replies":                                  "each reply, by member and dispatch",
	"replies.<node>.<dispatch>.dispatch":       "",
	"replies.<node>.<dispatch>.phase":          "",
	"replies.<node>.<dispatch>.note":           "the member's own summary of what it did",
	"replies.<node>.<dispatch>.outcome":        "the mission reply's outcome",
	"replies.<node>.<dispatch>.unmet":          "what the mission reply says was not met",
	"replies.<node>.<dispatch>.at":             "",
	"replies.<node>.<dispatch>.repos":          "the repositories the reply names",
	"replies.<node>.<dispatch>.raw":            "the reply file as written",
	"messages":                                 "the text of every dispatch and continue, by member and file name",
	"readback":                                 "the host's readback record: which members restated their brief, and in which dispatch",
	"fleetVerdict":                             "the host's audit of the machines after the run",
	"issues":                                   "the viewer's findings, most severe first. An issue outranks a claim",
	"issues[].severity":                        "`error`, `severe`, `warning` or `info`",
	"issues[].code":                            "defined in `issueDefs`",
	"issues[].message":                         "",
	"issues[].node":                            "",
	"issues[].dispatch":                        "",
	"timelineValid":                            "false when message times cannot be trusted; the page then draws no timeline",
	"issueDefs":                                "one line defining each issue code",
	"traces":                                   "what cs-tracer read from each member's transcript",
	"traces.tool":                              "the tracer's version",
	"traces.sessions":                          "one per session, in the order the page numbers their steps",
	"traces.sessions[].id":                     "the session, and the name of its file in `traces/`",
	"traces.sessions[].node":                   "the member it belongs to",
	"traces.sessions[].source":                 "the CLI: `claude-code`, `codex` or `opencode`",
	"traces.sessions[].page":                   "its trace page",
	"traces.sessions[].parent":                 "the session that spawned it, for a subagent",
	"traces.sessions[].parentEventIndex":       "the step in the parent that spawned it",
	"traces.sessions[].startedAt":              "",
	"traces.sessions[].endedAt":                "",
	"traces.sessions[].model":                  "",
	"traces.sessions[].events":                 "how many events the trajectory holds",
	"traces.sessions[].strip":                  "the session's steps",
	"traces.sessions[].strip[].i":              "the step's index in its trajectory, and `#ev-<i>` on its trace page",
	"traces.sessions[].strip[].kind":           "`user`, `assistant`, `thinking`, `tool_call`, `system`, `meta` or `turn_end`",
	"traces.sessions[].strip[].ts":             "when",
	"traces.sessions[].strip[].workMs":         "the time this step accounts for: from the end of the previous piece of work to the end of this one. Tool calls running at once overlap, so these do not sum to a session's work",
	"traces.sessions[].strip[].idleMs":         "time after this step before the next turn began",
	"traces.sessions[].strip[].activeMs":       "the part of `workMs` the model spent generating, where the CLI records it",
	"traces.sessions[].strip[].turnEnd":        "the step ends a turn",
	"traces.sessions[].strip[].error":          "the step failed; `facts.json` classes every one",
	"traces.sessions[].strip[].label":          "the tool name, or the error's kind such as `server_error`",
	"traces.sessions[].strip[].subtask":        "the step spawned a subagent",
	"traces.sessions[].strip[].childSessionId": "that subagent's session",
	"traces.sessions[].strip[].text":           "the step's first line, or its command, cut short",
	"traces.sessions[].strip[].wait":           "the step is a call to the harness's wait",
	"traces.sessions[].strip[].addr":           "the step's address on the page; absent for a step the page does not draw: one with no time, a turn end, or `meta` and `system` steps",
	"traces.sessions[].strip[].idleAddr":       "the address of the idle mark after it",
	"traces.anchors":                           "where each dispatch shows in the traces",
	"traces.anchors[].node":                    "",
	"traces.anchors[].dispatch":                "",
	"traces.anchors[].kind":                    "`sent`, `arrived`, `replied` or `accepted`",
	"traces.anchors[].session":                 "",
	"traces.anchors[].i":                       "the step, by its `i`",
}

var factsDocs = map[string]string{
	"schemaVersion":                        "the version of this document's shape",
	"campaign":                             "the campaign's name",
	"elapsed":                              "from the first protocol event to the last",
	"elapsed.from":                         "",
	"elapsed.to":                           "",
	"elapsed.duration":                     "",
	"elapsed.fromAddr":                     "",
	"elapsed.toAddr":                       "",
	"totals":                               "the run's totals",
	"totals.toolCalls":                     "",
	"totals.toolOutputBytes":               "bytes the tools returned to the models. Not tokens",
	"totals.outputTokens":                  "tokens the models wrote. Not tool output",
	"totals.failedSteps":                   "failed steps by class",
	"members":                              "one per node, with its sessions",
	"members[].node":                       "",
	"members[].role":                       "",
	"members[].cli":                        "",
	"members[].work":                       "the tracer's work time for each session, summed over the member's sessions",
	"members[].idle":                       "the time between its turns",
	"members[].wait":                       "the part of work spent in the harness's wait call. The orchestrator spends most of its turn there",
	"members[].idleShare":                  "idle as a share of this member's own work plus idle, from 0 to 1",
	"members[].steps":                      "",
	"members[].toolCalls":                  "",
	"members[].toolOutputBytes":            "",
	"members[].outputTokens":               "",
	"members[].sessions":                   "the same, per session",
	"members[].sessions[].id":              "",
	"members[].sessions[].source":          "",
	"members[].sessions[].model":           "",
	"members[].sessions[].work":            "",
	"members[].sessions[].idle":            "",
	"members[].sessions[].steps":           "",
	"members[].sessions[].toolCalls":       "",
	"members[].sessions[].toolOutputBytes": "",
	"members[].sessions[].outputTokens":    "",
	"members[].sessions[].page":            "",
	"dispatches":                           "every dispatch, longest first; one never replied to runs to the end of the run",
	"dispatches[].node":                    "",
	"dispatches[].dispatch":                "",
	"dispatches[].phase":                   "",
	"dispatches[].openedAt":                "",
	"dispatches[].repliedAt":               "",
	"dispatches[].duration":                "",
	"dispatches[].continues":               "",
	"dispatches[].restarts":                "",
	"dispatches[].addr":                    "",
	"idleGaps":                             "the ten longest gaps between a member's turns, longest first",
	"idleGaps[].idle":                      "",
	"idleGaps[].addr":                      "the idle mark on the page",
	"idleGaps[].after":                     "the step the gap follows",
	"failedSteps":                          "every step that failed, in session order. Each is a step reference plus `class` and `result`",
	"failedSteps[].class":                  "`provider` (the model's server failed), `account` (a rate limit), `guard` (the member's CLI refused the call), `command` (the member's own command failed) or `other`",
	"failedSteps[].result":                 "the start of what the call returned",
	"recovery":                             "every continue and restart the harness sent. The harness sends one when it judges a dispatch stalled",
	"recovery.policy":                      "the limits it acted under: continues and restarts allowed per dispatch, the seconds of quiet it calls a stall, and the most seconds a dispatch may sit behind a failing provider. Each is a limit, not a record of what the harness did",
	"recovery.policy.continueAttempts":     "",
	"recovery.policy.restarts":             "",
	"recovery.policy.stallSeconds":         "",
	"recovery.policy.providerWaitSeconds":  "",
	"recovery.events":                      "in time order",
	"recovery.events[].type":               "`continue` or `restart`",
	"recovery.events[].node":               "",
	"recovery.events[].dispatch":           "",
	"recovery.events[].at":                 "",
	"recovery.events[].addr":               "",
	"recovery.events[].sinceLastStep":      "the gap from that member's last recorded step to this event",
	"recovery.events[].lastStep":           "that step, and whether it errored",
	"recovery.events[].turnError":          "the failed step that ended that step's turn, when one did",
	"subagents":                            "every subagent a member spawned: a step reference plus `child`, the child's session",
	"subagents[].child":                    "",
	"repeatedCalls":                        "one member calling one tool with the same input three times or more, most first",
	"repeatedCalls[].node":                 "",
	"repeatedCalls[].tool":                 "",
	"repeatedCalls[].input":                "the input, cut short",
	"repeatedCalls[].count":                "",
	"repeatedCalls[].polling":              "the call is the harness's wait, which repeats by design. Only that call is marked: a member can wait in other ways, such as `sleep` and then a read of the same file",
	"repeatedCalls[].addrs":                "each call's step",
}

// The two shapes facts.json repeats, described once.
var durDocs = map[string]string{
	"ms":  "milliseconds",
	"hms": "the same, as h:mm:ss",
}

var stepRefDocs = map[string]string{
	"node":    "the member",
	"session": "its session",
	"at":      "when",
	"kind":    "the step's kind, as on the strip",
	"label":   "the tool name, or the error's kind",
	"error":   "whether the step failed",
	"text":    "its first line, or its command, cut short",
	"addr":    "the step's address on the page; absent for a turn end, which the page does not draw, and then `page` is the link to cite",
	"page":    "the step on its trace page",
}
